name: python-ChaBoDoc
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib>=3.9
  - numpy>=1.26.4
  - pytorch>=2.4
  - streamlit>=1.38
  - nltk>=3.9
  - dropbox>=11.36.1
